### ISSUE TITLE
Samsung Internal Graphics Issues

### ISSUE THREAD

**Issue by AbandonedCart** [skyline-emu/skyline#1964]
I'm leaving this here because I know it's not necessarily a skyline issue, but one it is experiencing. When testing games that "work" for a ROG Phone 5 (until I sold it), an identical setup had artifacts, tearing, and all the fun terminology for broken graphics on Samsung. Below is a comparison of the three devices tested.

- S22 Ultra
    - Qualcomm Snapdragon 8 Gen 1
    - Octa-core (1x3.00 GHz Cortex-X2 & 3x2.50 GHz Cortex-A710 & 4x1.80 GHz Cortex-A510) 
    - Adreno 730
    - 12GB RAM
    - 256GB storage

- Z Flip 3
    - Qualcomm Snapdragon 888
    - Octa-core (1x2.84 GHz Cortex-X1 & 3x2.42 GHz Cortex-A78 & 4x1.80 GHz Cortex-A55)
    - Adreno 660
    - 8GB RAM
    - 256GB storage

- ROG Phone 5
    - Qualcomm Snapdragon 888
    - Octa-core (1x2.84 GHz Cortex-X1 & 3x2.42 GHz Cortex-A78 & 4x1.80 GHz Cortex-A55)
    - Adreno 660
    - 16GB RAM
    - 256GB storage

All three devices were Android 12 at the time of testing, but the interesting part is that the Z Flip 3 and ROG Phone 5 specs are nearly identical. This is why I believe it to be a Samsung issue. Changing drivers had little to no impact on the issues for the Samsung devices.

**Comment by AbandonedCart** [comment]
https://user-images.githubusercontent.com/1173913/200312574-9b3a810a-861b-4a4e-b7d7-b89501c1f639.mp4

**Comment by JERD001** [comment]
After trying it out by myself (Tab S8) with default drivers and Realme drivers i can say that both of them present the same issue so it must be adreno 730 drivers issue, remember that the other devices you have have a different GPU and drivers so that might influence the end result.

**Comment by AbandonedCart** [comment]
@JERD001 The point of listing the specs was to show that the ROG and Z Flip do **not** have a different GPU, but only one has problems. Typically, the drivers are provided by Qualcomm, not Samsung or Asus.

**Comment by AbandonedCart** [comment]
In case it's of any interest for R&D or whatever, here is a lot from the same game on the S22 Ultra

[emulation.sklog.zip](https://github.com/skyline-emu/skyline/files/9961622/emulation.sklog.zip)

**Comment by FacuM** [comment]
I can only agree that this is actually accurate, Samsung devices seem to have some sort of difference within their Adreno drivers (or maybe it's just a kernel bug?) that prevents them from running NS games properly. I've seen plenty of people playing Super Mario Odissey just fine on older devices and even older version of the emulator itself without major issues, yet my **Samsung Galaxy Fold 4** just won't run properly (got graphical issues everywhere, even a weird yellow tint all over the render), this is happening regardless of which drivers I try.

Here's some proof  (**WARNING:** loud glitched audio):
https://youtu.be/sxp9qh_v_1s

**Comment by ikhoeyZX** [comment]
After update skyline v1564 & v1565, all my games got blank with 60fps frezee

**Comment by AbandonedCart** [comment]
It appears some of the changes (both merged and still pending) do make a drastic improvement in overcoming the firmware. The stuttered tearing has become more defined into an overly zoomed and unfocused image. Not being able to root either device, I can't test kernel changes to see if it that would make it clear. Kudos @bylaws for finding ways to make it clear enough to not cause a seizure, though.

**Comment by Nobiy1** [comment]
in sonic mania just do a constant red screen.

**Comment by AbandonedCart** [comment]
> in sonic mania just do a constant red screen.

Is it something that is present on a Samsung device, but not on other devices with the same hardware?

**Comment by PixelyIon** [comment]
A bit late of a reply but I'm guessing this is due to driver differences somehow? Given how old the issue is I would imagine some things are fixed by now, if so you'll probably want to close the issue.

**Comment by AbandonedCart** [comment]
I have to see if the error is still the same, but the blurriness is still there. It's slowly improving in spots, though, so there have definitely been positive changes.

**Comment by AbandonedCart** [comment]
Through a combination of recent changes and installing the appropriate GameDriver app for Samsung ([Adreno](https://play.google.com/store/apps/details?id=com.samsung.gamedriver.S11Adreno650) / [Mali](https://play.google.com/store/apps/details?id=com.samsung.gamedriver.S11MaliG77)), most of the issues are now gone.

**Comment by FacuM** [comment]
> Through a combination of recent changes and installing the appropriate GameDriver app for Samsung ([Adreno](https://play.google.com/store/apps/details?id=com.samsung.gamedriver.S11Adreno650) / [Mali](https://play.google.com/store/apps/details?id=com.samsung.gamedriver.S11MaliG77)), most of the issues are now gone.

Definitely still an issue for me on my **Galaxy Z Fold4** using the **Qualcomm v676.13 Vulkan driver**.

![ss1](https://user-images.githubusercontent.com/3741108/233424602-c2d90218-176d-4d99-9b5b-5a019e2cb6d8.jpg)
![ss2](https://user-images.githubusercontent.com/3741108/233424612-5bef63a3-0c3d-4af4-b3ec-20fe431169a3.jpg)

**Comment by FacuM** [comment]
> That's likely a different issue. The original issue was that the screen looked like it was being viewed through a kaleidoscope and was improved to looking like unfocused binoculars. That looks like more of a tint issue.

Oh, got it. I'm gonna create a new issue!

**Comment by PixelyIon** [comment]
@FacuM That issue seems more like general Skyline issues without `texman` rather than some device-specific issue that isn't present on other GPUs whatsoever and has a differing cause. Therefore it's better to hold off on reporting issues regarding it, also per-game issues would go to our other repository: https://github.com/skyline-emu/skyline-games-list/issues.

**Comment by FacuM** [comment]
> @FacuM That issue seems more like general Skyline issues without `texman` rather than some device-specific issue that isn't present on other GPUs whatsoever and has a differing cause. Therefore it's better to hold off on reporting issues regarding it, also per-game issues would go to our other repository: https://github.com/skyline-emu/skyline-games-list/issues.

Oh I've just read a bit on a Reddit thread about `texman`, I didn't know that was a thing. I was under the impression that the game should work fine on my device as there are a couple of videos floating around YouTube that made it look like it was working great, like [this one](https://youtu.be/fReRCe2Sigc). Am I missing anything?

**Comment by PixelyIon** [comment]
Textures tend to fix themselves if you jump off a cliff in the game which causes a level reload, I'm not entirely sure how it does just work directly in that case but it's probably a fluke. We should run SMO fine in theory after `texman` is done which should be sometime soon:tm:.

**Comment by FacuM** [comment]
> Textures tend to fix themselves if you jump off a cliff in the game which causes a level reload, I'm not entirely sure how it does just work directly in that case but it's probably a fluke. We should run SMO fine in theory after `texman` is done which should be sometime soon™️.

Ah, cool, thanks for the reply! I'm gonna keep trying then. :)
