### ISSUE TITLE
Mali GPU crash

### ISSUE THREAD

**Issue by ChrisM20** [skyline-emu/skyline#987]
A progress on repair?, I have noticed that version #1023 comes to appear a few seconds more the game screen, if it recorded screen it closes immediately, I hope to know about a possible solution to the Mali gpu.

Huawei Mate 20
![Screenshot_20220411_225312_skyline emu](https://user-images.githubusercontent.com/60308449/162877102-40d33fc7-1eec-4866-aec2-7506c6f9a2d2.jpg)

Update about log:
Log debug:
[emulation.log](https://github.com/skyline-emu/skyline/files/8474236/emulation.log)

And log Verbose:
[emulationlog.zip](https://github.com/skyline-emu/skyline/files/8474252/emulationlog.zip)

Searching a little these two logs appear, trying to open the game sometimes takes a little longer, sometimes less and sometimes without anything, in the attempts you get to hear the voice of sega

**Comment by PixelyIon** [comment]
Can you get a log from Skyline?

**Comment by ChrisM20** [comment]
> Can you get 

> Can you get a log from Skyline?

Yes, 2 appear changing the log level, it is already updated

**Comment by PixelyIon** [comment]
Are you on the latest build, these logs are incomplete? You should take a debug log also restart the application after changing the log level, there's a bug where it won't update it till it's restarted.

**Comment by ChrisM20** [comment]
> Are you on the latest build, these logs are incomplete? You should take a debug log also restart the application after changing the log level, there's a bug where it won't update it till it's restarted.

I think that if the system was confused by not restarting but I have already updated the files with new ones and restarting the app only debug and Verbose appear without log error, and the version is the latest #1023.

**Comment by SavitarCN** [comment]
El Mali-g76 no ejecuta ningún juego con el skyline los FPS al entrar a un juego sobrepasan lo normal llegando a más de 100 lo cual deja el juego congelado algunos quedan en blanco y otros cierran nomás: Sonic Mania
![Screenshot_2022-04-15-10-56-11-461_skyline emu](https://user-images.githubusercontent.com/103731882/163592849-f4331124-32fe-4af3-8314-d4cc3d184af7.jpg)

**Comment by huawdinho** [comment]
I have same problem, pls fix mali gpus compatibility

**Comment by HalogenGam3r** [comment]
[emulation.log](https://github.com/skyline-emu/skyline/files/8505840/emulation.log)

Here's log.

**Comment by demonx77** [comment]
> El Mali-g76 no ejecuta ningún juego con el skyline los FPS al entrar a un juego superado lo normal llegando a más de 100 lo cual deja el juego congelado algunos quedan en blanco y otros cierran nomás: Sonic Mania ![Captura de pantalla_2022-04-15-10-56-11-461_skyline emu](https://user-images.githubusercontent.com/103731882/163592849-f4331124-32fe-4af3-8314-d4cc3d184af7.jpg)

me pasa exactamente igual con un mali g95

**Comment by ibmeto** [comment]
Any updates on the mali gpu fix, please?

**Comment by HalogenGam3r** [comment]
Still nothing. It will probably be fixed in 1-3 weeks.

**Comment by ibmeto** [comment]
Thanks for the reply

> Still nothing. It will probably be fixed in 1-3 weeks.

**Comment by demonx77** [comment]
please support for mediatek systems :(

**Comment by Benjam1l0s** [comment]
I have a mali g77 and it does not open any game, it does not work in gpus mali

**Comment by PixelyIon** [comment]
I am currently working on a fix.

**Comment by demonx77** [comment]
> Actualmente estoy trabajando en una solución.

fantastic !!!👍👍👍

**Comment by huchao2007** [comment]
麒麟9000e打开游戏黑屏

**Comment by huchao2007** [comment]
Kirin 9000e opens the game black screen

**Comment by Artemmisuk** [comment]
Sonic mania kirin 820 ранее работал щас нет сделайте чтобы работал и оптимизируйте под процессор.

**Comment by PixelyIon** [comment]
As of 23c9388caf30c2d18b49e659b86a339e5d3d4e90, Mali should be partially fixed. There are still glitches left and we're still working on them.

**Comment by ibmeto** [comment]
> As of [23c9388](https://github.com/skyline-emu/skyline/commit/23c9388caf30c2d18b49e659b86a339e5d3d4e90), Mali should be partially fixed. There are still glitches left and we're still working on them.

Thanks for the update. Which apk is partially fixed?

**Comment by S22Ultraexynos** [comment]
S22 ultra exynos,  black screen or crash

**Comment by S22Ultraexynos** [comment]
And s22 ultra exynos has eclipse gpu not mali
![Screenshot_20220504-125125_ColorNote](https://user-images.githubusercontent.com/104895136/166659993-ed818d04-bec5-467e-afa2-bd2cc1e26d2b.jpg)

**Comment by PixelyIon** [comment]
We are aware of the S22 Exynos devices being broken, this is due to a SoC bug that Samsung needs to fix. We have reported this to them but it up to them to fix this.

**Comment by S22Ultraexynos** [comment]
> We are aware of the S22 Exynos devices being broken, this is due to a SoC bug that Samsung needs to fix. We have reported this to them but it up to them to fix this.

Oh, okay, but anyways you're doing really good job developing this emulators, thank you.

**Comment by OraOra45** [comment]
is it fixed now?

**Comment by huchao2007** [comment]
No, only play very few games, many games still flashback发自我的手机-------- 原始邮件 --------发件人： OraOra45 ***@***.***>日期： 2022年5月5日周四 12:43收件人： skyline-emu/skyline ***@***.***>抄送： huchao2007 ***@***.***>, Comment ***@***.***>主    题： Re: [skyline-emu/skyline] Mali GPU crash (Issue #987)
is it fixed now?

**Comment by PixelyIon** [comment]
This has been mostly fixed as of https://github.com/skyline-emu/skyline/commit/7206ab4c674c21fc2a4ac5387939782886844f1d, the corresponding [CI build 1073](https://github.com/skyline-emu/skyline/runs/6307293603). Certain issues such as Sonic Mania crashing are known and will be fixed in the future.

**Comment by StringLibrary** [comment]
Not only is it sonic mania but more games others do not open Others with the black screen error and so on but I trust that everything will be solved with the passage of time since it is a project Others with the black screen error and so on but I trust that everything will be solved over time 😃

**Comment by mmtrt** [comment]
Logs per game with `CI Build 1073`

GPU `Mali G57 MC2`

games tested
```
Super meat bot
Monster world iv
Sonic mania
```
[skyline-g57-mc2.zip](https://github.com/skyline-emu/skyline/files/8637839/skyline-g57-mc2.zip)

**Comment by PixelyIon** [comment]
We're aware about all these issues and they will be fixed in time, there's some inter-team coordination required to fix this. At the moment we don't require logs since the cause of all crashes is the exact same.

**Comment by demonx77** [comment]
Celeste 30 fps estable, en Mali G95 . extraordinario el avance.muchas gracias 👍👍

**Comment by huchao2007** [comment]
Celeste Kirin 9000 can be run发自我的手机

**Comment by Wilyicaro** [comment]
My phone with Mediatek G90T processor still has the same problem, with these new builds, but the log finally had a lot of differences, so I think it will be useful
[Skylines_log.txt](https://github.com/skyline-emu/skyline/files/8646188/Skylines_log.txt)

**Comment by Wilyicaro** [comment]
It could be that I'm doing something wrong, like using the wrong/corrupted rom, some configuration I didn't do, some problem with the prod keys and title keys.....

**Comment by StringLibrary** [comment]
OneFor processors, cpu as they want to tell you will make the emulator compatible in the future since they are doing an excellent job with this emulator but for that processors since in kirin710 if it is very low the games like celeste have some small graphic errors but not annoying but I still love this project 😄

**Comment by S22Ultraexynos** [comment]
![Screenshot_20220509-122103_Skyline](https://user-images.githubusercontent.com/104895136/167380390-2ecd491a-2d23-4055-b954-7c381e848424.jpg)
Celeste s22 ultra exynos, just installed latest firmware with latest emu version ,still nothing works,just graphical artifacts, still hoping for some fix, because early versions allowed to play some 2d games.

**Comment by Jannatuul** [comment]
Cyber shadow and some 2d games are working on my galaxy note 9 but from past 2 days not a single game is loading

**Comment by StringLibrary** [comment]
I installing the new skyline update enter to celeste for Create data and everything normal I go to the folder skyline.emu and paste there my data of the previous version as far as I stay this I had done several times then do not worry but I when entering the game I found this 
![Screenshot_20220510_170055_skyline emu](https://user-images.githubusercontent.com/103220290/167729736-f31aeeb9-4c7f-4e39-858e-4bb57af8dddb.jpg)
Yes that. And what is that problem or error?

**Comment by IgorLumine** [comment]
So, has anyone manange to get skyline to work on Mediateck devices? I tried with many games but nothing works
Ps: I am using a poco x3 gt with a dimensity 1100
![Screenshot_2022-05-11-09-41-03-446_skyline emu](https://user-images.githubusercontent.com/104659551/167853044-f8b47aea-e435-4827-a708-2baca1caee85.jpg)

**Comment by demonx77** [comment]
Toki Tori 

> 

Toki Tori run 30 fps stable Mali G95

**Comment by HAHAIMPOOR** [comment]
What skyline emulator build are you using to run with Mali GPU

**Comment by demonx77** [comment]
> What skyline emulator build are you using to run with Mali GPU

latest update

**Comment by ibmeto** [comment]
> > What skyline emulator build are you using to run with Mali GPU
> 
> latest update #1099

Not working yet on note 9

**Comment by HAHAIMPOOR** [comment]
Yeah the #1099 build is not working. What did you download? Normal or debug?

**Comment by Wilyicaro** [comment]
On my cell phone with Mediatek G90T it also doesn't work at all in released builds, in Sonic Mania sometimes I can see and hear the Sega intro, but nothing else, and that hasn't changed since they said here that it was partially fixed.

**Comment by Wilyicaro** [comment]
A useful information is that from build #897 this crash started for me, in the previous ones it worked normally even with low emulation speed

**Comment by demonx77** [comment]
> Yeah the #1099 build is not working. What did you download? Normal or debug?

normal

**Comment by HalogenGam3r** [comment]
I played Axiom Verge for some minutes, and it then freezes.

**Comment by StringLibrary** [comment]
This is nose normal or brutal because in the mali processors it already shows the intro of hungry shark world That shows that capturing all this is advanced in these processors. 
![Screenshot_20220513_180021_skyline emu](https://user-images.githubusercontent.com/103220290/168399636-ee172e9e-2c11-46d8-a5f1-c7773084c8f8.jpg)
Ah the test was on a bad mali-G51 don't believe it

**Comment by PrithivMBBS** [comment]
My device is Android 10 but It can't boot sonic mania,
Sometimes the Sega logo appear and it instantly crashes but the game was playable when skyline was initially booting 2D and 3d games

**Comment by PrithivMBBS** [comment]
Do anyone know what is the problem

**Comment by oloketuyimoyosi** [comment]
When would the new update come out that fixes some games in Mail GPU?

**Comment by oloketuyimoyosi** [comment]
> Does anyone know what is the problem

It is due to the update, For me, it doesn't work on My mail Phone and also Skyline is meant for Snapdragon processors so mail will have to wait.
But if you what to play sonic mania at 17 fps u should try build #880.

**Comment by darkraiy** [comment]
Mali-G77 no funciona aún 
![Screenshot_2022-05-14-13-43-46-529_skyline emu](https://user-images.githubusercontent.com/83917376/168446256-9bdd184d-3ace-42c5-8e41-2f067a2e44c0.jpg)

**Comment by oloketuyimoyosi** [comment]
> 

What game?

**Comment by darkraiy** [comment]
> > 
> 
> ¿Que juego?

Ni un solo juego solo pantalla negra y ni un fps luego se cierra

**Comment by Benjam1l0s** [comment]
> 

También lo mismo en mali g77

**Comment by StringLibrary** [comment]
Well I install the latest version of the skyline and everything goes normal as the previous games that go to 20fps as the following: Celeste, super crush K.O, vvvvvvv, and among other games that I do not remember the name cuphead is still blocked but already Advances some FPS and then it crashes ah and I am doing the tests on a GPU mali-51 also depends on the ram and the Android version you have to remember that the developers recommend Android 11 but I still use the 10 and it remains the same 
You have to see what happens with the passing of days, weeks and months or who knows years xD in the end
![Screenshot_20220514_175837_skyline emu](https://user-images.githubusercontent.com/103220290/168450644-45b41030-c4bd-4a65-8d64-b4627e720190.jpg)
![Screenshot_20220514_175653_skyline emu](https://user-images.githubusercontent.com/103220290/168450645-c971e8b7-0106-40bf-b625-7f155e984056.jpg)
![Screenshot_20220514_175631_skyline emu](https://user-images.githubusercontent.com/103220290/168450647-9a41c110-014a-4570-b3dc-50e5b4fcd141.jpg)
![Screenshot_20220514_175542_skyline emu](https://user-images.githubusercontent.com/103220290/168450650-3dedb655-2d52-4ff8-8c56-7d6a6f21d566.jpg)
![Screenshot_20220514_175523_skyline emu](https://user-images.githubusercontent.com/103220290/168450651-0562eaf5-6602-4d56-b20d-bd01d6ecb104.jpg)

**Comment by IgorLumine** [comment]
Apparently Skyline is completely broken on Mali G77, can some dev fix this? Please (;

**Comment by PixelyIon** [comment]
It will be fixed in time but the developer who has a Mali device and will work on things that Mali needs like software BCn decoding is busy with University work so it'll take some time before this can be fixed.

**Comment by demonx77** [comment]
> Se solucionará a tiempo, pero el desarrollador que tiene un dispositivo Mali y trabajará en las cosas que Mali necesita, como el software de decodificación BCn, está ocupado con el trabajo de la Universidad, por lo que pasará algún tiempo antes de que se pueda solucionar.

Thank you very much for the effort and dedication, all that remains is to wait patiently until the developer is free. It is an incredible job that you are doing👍👍

**Comment by alfhashut** [comment]
Any updates on the mali gpu fix? (sorry)

**Comment by oloketuyimoyosi** [comment]
I have a question, why does super crush K.O work on mail Gpu while games like foragers, Sonic, and Shovel Knight don't work on mail GPU

**Comment by K11MCH1** [comment]
> I have a question, why does super crush K.O work on mail Gpu while games like foragers, Sonic, and Shovel Knight don't work on mail GPU

None of these except probably SC K.O (i think) works for Mali.
Because Skyline does not completely support Mali yet.
Forager does not even work for Snapdragon either yet.

**Comment by kyroken** [comment]
I can play celeste and its ok. I can go up to 50fps. Let's just wait for the fix we dont need to rush them. I know one day it will be fixed. 

My phone : HUAWEI NOVA 5T
CHIPSET : KIRIN 980
GPU: MALI G76 MP10

![Screenshot_20220516_170000_skyline emu](https://user-images.githubusercontent.com/66888132/168558859-738baf50-4e57-45f3-89f1-ab0809721026.jpg)

**Comment by StringLibrary** [comment]
To talk about the negative or the problems that exist when there is progress 
![Screenshot_20220516_100536_skyline emu](https://user-images.githubusercontent.com/103220290/168624775-493f91d2-56fe-4eb5-900b-66081af764fd.jpg)
I have already reached the summit or chapter 7 and boy did it cost but that shows that this problem is being solved  
![Screenshot_20220515_170635_skyline emu](https://user-images.githubusercontent.com/103220290/168625541-c04da578-bb95-4612-8ca8-50c390163963.jpg)
This is another game that is already compatible with the emulator is the megaman legacy collection on the home screen has fatal errors and goes to low fps this if it is advanced 😃

**Comment by HAHAIMPOOR** [comment]
Does skyline emulator support Dimensity chipset?

**Comment by OraOra45** [comment]
any updates?

**Comment by StringLibrary** [comment]
> any updates?

Check the discord and you will know why

**Comment by Farnezin** [comment]
any updates about the compatibility with the poco x3 gt?

**Comment by MrEldlich** [comment]
Skyline emulator doesn't work on Samsung A30

**Comment by Farnezin** [comment]
dimensity 1100 still not working (poco x3 gt)

**Comment by IgorLumine** [comment]
> dimensity 1100 still not working (poco x3 gt)

Wich version of MiUi are you using? I think it may be a problem with the newer version

**Comment by Alimaster1999** [comment]
I hope the developers work on my money as soon as possible. I really need to play Nintendo Switch games. Thank you for your great effort. I appreciate that

**Comment by Farnezin** [comment]
> > dimensity 1100 still not working (poco x3 gt)
> 
> Wich version of MiUi are you using? I think it may be a problem with the newer version

I'm using the 13.0.3 (the latest ;-;) i don't like that the system updates for itself

**Comment by SinUsername** [comment]
How good is this equipment since they started with the decoding BCn and work many games whether they reach the menu or Intro of the same I like and also because I am doing the tests on my cell phone that is a Huawei p30 lite 
With 4GB ram, 128GB of core storage or cpu is a kirin710, Android 10 and of course GPU Mali to be exact the MG-51 that if already tried 3d games and do not give the only one that goes well between 10 and 6 fps is the Rolling sky 
Also another game that walks is this: 
![Screenshot_20220530_200437_skyline emu](https://user-images.githubusercontent.com/94080806/171074379-6feea39f-a84a-4ad6-b9c5-b8d585661756.jpg)
![Screenshot_20220530_200712_skyline emu](https://user-images.githubusercontent.com/94080806/171074381-1c9251c9-2861-45fa-85fe-a3bac5866de3.jpg)
![Screenshot_20220530_200741_skyline emu](https://user-images.githubusercontent.com/94080806/171074384-8f98aa4d-1726-419b-a192-0395723540b4.jpg)

but I understand that it still does not work in the emulator or it already does because it already wants to work for me but that if I have to do something strange to be able to enter the game in fin congratulations team.

**Comment by Farnezin** [comment]
> > > dimensity 1100 still not working (poco x3 gt)
> > 
> > 
> > Wich version of MiUi are you using? I think it may be a problem with the newer version
> 
> I'm using the 13.0.3 (the latest ;-;) i don't like that the system updates for itself, and even with the build #1152 i can't play

Update: the poco x3 gt is working in the newer version of MIUI and of the skyline (13.0.4) and build 1152

**Comment by ChrisM20** [comment]
Does anyone have any information on the possible solution?

**Comment by SinUsername** [comment]
> Does anyone have any information on the possible solution?

They are already in it and started the decoding BCn quiet that they are already in it it only remains to waitThey are already in it and started the decoding BCn quiet that they are already in it it only remains to wait 😄

**Comment by OraOra45** [comment]
> Does
just wait

**Comment by HAHAIMPOOR** [comment]
Does Dimensity 1200 work on skyline emulator?

**Comment by demonx77** [comment]
> ¿Funciona Dimensity 1200 en el emulador de horizonte?

en Mali G95 ya corren muchos juegos exelentes.😍🥳

**Comment by demonx77** [comment]
> > > ¿Funciona Dimensity 1200 en el emulador de horizonte?
> > 
> > 
> > en Mali G95 ya corren muchos juegos exelentes.😍🥳
> 
> ¿que juegos?

bastion , celeste, hollow, steam World, Toki tori, Shinobi (Sega Ages), out ruta (Sega Ages), sonic2 (Sega Ages),

**Comment by oloketuyimoyosi** [comment]
That doesn't make sense.it can't run sonic 2 (sega ages) and can't run any game made by Sega on Mail GPU.

**Comment by oloketuyimoyosi** [comment]
And Steamworld isn't that playable, Was able to get in-game for some minutes then it crashes.

**Comment by oloketuyimoyosi** [comment]
So how can a Mail GPU run does games. Send me a screenshot of those games.

**Comment by demonx77** [comment]
> Eso no tiene sentido. No puede ejecutar sonic 2 (edades de sega) y no puede ejecutar ningún juego creado por Sega en Mail GPU.

para empezar,usted que dispositivo movil tiene ???

**Comment by oloketuyimoyosi** [comment]
Tecno pova, G52 Mail.

**Comment by demonx77** [comment]
> Tecno pova, G52 Mail.

yyy bueno, hay está el porque no le funciona, yo tengo G95, que es un equivalente a un snapdragon 730g.Y el G52 equivalente a un snapdragon 600 o menor.

**Comment by KYM201** [comment]
Pero si el mío es un 860 tiene que funcionar mejor por decirlo haci

**Comment by demonx77** [comment]
> Pero si el mío es un 860 tiene que funcionar mejor por decirlo haci 

860 snapdragon? si es así no sabría que decirle,ya que no cuento con un móvil con esa gpu , y este hilo es sobre Mali Mediatek

**Comment by oloketuyimoyosi** [comment]
Could you send a screenshot of you playing SONIC 2( sega ages)and out run(sega ages)

**Comment by oloketuyimoyosi** [comment]
And Mail doesn't have Bcn, So I was surprised  when u said that u could play sonic 2 on a Mail device.But can u play sonic Mania on a G95

**Comment by demonx77** [comment]
> Y Mail no tiene Bcn, así que me sorprendió cuando dijiste que podías reproducir Sonic 2 en un dispositivo Mail. Pero, ¿puedes reproducir Sonic Mania en un G95?

![Uploading Screenshot_20220604-133110.png…]()
![Uploading Screenshot_20220604-133427.png…]()

**Comment by demonx77** [comment]
Toki Tori se rompio en las 2 últimas actualizaciones 1167 y 1168 :(

**Comment by oloketuyimoyosi** [comment]
I can't open the screenshot.

**Comment by demonx77** [comment]
![Uploading Screenshot_20220604-133427.png…]()

**Comment by oloketuyimoyosi** [comment]
Just send it to my discord

**Comment by demonx77** [comment]
![Screenshot_20220604-133427_640x280](https://user-images.githubusercontent.com/104382169/172022861-ce993ba1-d44f-46ac-b019-9ac8a5fdc94b.png)

**Comment by demonx77** [comment]
![Screenshot_20220604-133110_240x546](https://user-images.githubusercontent.com/104382169/172022886-354c2fb9-319c-4c01-b5db-c40c8a3b009f.png)

**Comment by oloketuyimoyosi** [comment]
What build

**Comment by demonx77** [comment]
1158

**Comment by oloketuyimoyosi** [comment]
Does hollow knight work

**Comment by demonx77** [comment]
> ¿Funciona Hollow Knight?

si

**Comment by oloketuyimoyosi** [comment]
Does pokemon let go Pikachu work

**Comment by demonx77** [comment]
> ¿Funciona Pokémon Let Go Pikachu?

no, xD solo pantallazo del comienzo xD

**Comment by oloketuyimoyosi** [comment]
Damn, In my G52 it doesn't even boot sonic 2

**Comment by oloketuyimoyosi** [comment]
Can u run sonic mania

**Comment by demonx77** [comment]
> puedes ejecutar sonic mania

en algunas versiones anteriores, principalmente en las primeras si, ahora no

**Comment by oloketuyimoyosi** [comment]
I don't understand how this is possible.

**Comment by demonx77** [comment]
![Screenshot_20220604-163908_320x140_640x280](https://user-images.githubusercontent.com/104382169/172023205-363c8b0f-bca0-4235-bc39-9824521225ba.png)

**Comment by oloketuyimoyosi** [comment]
Does it go ingame

**Comment by eazymo** [comment]
phone: p30 pro mali G76

skyline version: 1068

games tested

working games:
 
 celeste
 vvvvvvv
 stardash
 ScourgeBringer
 daggerhood
 kamiko
 axiom verge
 binding of Isaac rebirth
 gunslugs2
 _______________________
run but are very slow:

residual
cyber shadow
jumpking
iconoclast
steredenn
blossom tales
___________________________
not working Instant crash

sonic mania
gunlord x
Reed 2
binding of Isaac: afterbirth+
slain
sky force reloaded
carto

**Comment by oloketuyimoyosi** [comment]
Does it work

**Comment by VRonaldoC** [comment]
![Screenshot_2022-06-10-09-29-29-241_skyline emu](https://user-images.githubusercontent.com/105024658/173089262-1769e65a-da73-4e9e-89ff-aafc1eaa87ec.jpg)
SONIC MANIA crashed after leaving the logo, sometimes it doesn't start, but the improvement is noticeable xD

**Comment by darkraiy** [comment]
Ni un solo juego me funciona en mediatek Dimensity 1200 ni si quiera un solo fps

**Comment by SinUsername** [comment]
![Screenshot_20220610_110300_skyline emu](https://user-images.githubusercontent.com/94080806/173106554-030ac305-9375-4670-8fed-5adc10a6a046.jpg)
The rayman legends is already wanting to work on Mali GPU
In case you ask me I tried the game on this device: https://m.gsmarena.com/huawei_p30_lite-9545.php

**Comment by VRonaldoC** [comment]
> Ni un solo juego me funciona en mediatek Dimensity 1200 ni si quiera un solo fps

![Screenshot_2022-06-10-11-14-15-398_skyline emu](https://user-images.githubusercontent.com/105024658/173138305-082f2918-3698-4e1b-ba67-587d9d90b65f.jpg)
12 FPS on cuphead , Mediatek Dimensity 1100

**Comment by darkraiy** [comment]
> 

No sabía voy a checar

**Comment by SinUsername** [comment]
![Screenshot_20220612_083421_skyline emu](https://user-images.githubusercontent.com/94080806/173237686-d0fd9dae-833e-4e39-aa49-9e9b28622590.jpg)
![Screenshot_20220612_083518_skyline emu](https://user-images.githubusercontent.com/94080806/173237687-fba6441b-da5e-4053-943e-9ab531b8183c.jpg)
![Screenshot_20220612_083710_skyline emu](https://user-images.githubusercontent.com/94080806/173237689-463933e0-79fe-4339-913b-a19336fe4bce.jpg)
Esto es bueno 😁😌😊

**Comment by ChrisM20** [comment]
I didn't think cuphead would run but at least it works, the problem is that it usually exits and only sometimes I get a little further like the new game menu, the sound works normally

Huawei Mate 20 / Mali g76
![Screenshot_20220613_015259_skyline emu](https://user-images.githubusercontent.com/60308449/173297040-5c4398fa-8288-40cc-9bbc-e8c878941bfb.jpg)

**Comment by iNoelXD** [comment]
> ![Screenshot_20220604-163908_320x140_640x280](https://user-images.githubusercontent.com/104382169/172023205-363c8b0f-bca0-4235-bc39-9824521225ba.png)
> 
> Pikachu l,go

![Screenshot_2022-06-12-20-35-43-657_skyline emu](https://user-images.githubusercontent.com/89407203/173464986-15af678c-fdbd-475d-b0af-90edeffa4d62.jpg)
Same for lets go eeveee mali g52, i know that this is because gpu incompatibility but its ok

**Comment by SinUsername** [comment]
This good.
![Screenshot_20220613_215157_skyline emu](https://user-images.githubusercontent.com/94080806/173483820-da90d611-8b38-48b7-ba79-4ad1af8ec140.jpg)
![Screenshot_20220612_164205_skyline emu](https://user-images.githubusercontent.com/94080806/173483830-ff41f8d0-cf90-49ab-b481-693743525e3f.jpg)
![Screenshot_20220613_212212_skyline emu](https://user-images.githubusercontent.com/94080806/173483834-b32fdc3d-09bb-446c-af45-fde0423d1139.jpg)
But not much since they do not advance much games like shantae that are already working at the moment ami only sends me the sound of the start and breaks or clashes but this is good. 
Muy bueno

**Comment by blink62** [comment]
crash latest build on my redmi note 10 5g, trying to play animal crossing

**Comment by Realityboostty885348** [comment]
> ![Screenshot_20220604-133427_640x280](https://github.com/assets/104382169/ce993ba1-d44f-46ac-b019-9ac8a5fdc94b)

I'm try play that white screen apeared

**Comment by ibmeto** [comment]
With the latest build, I can't get any game I have to run. Sonic mania, cuphead celeste....

I have a exynos note 9

**Comment by AdriFarofenix23** [comment]
Please someone can fix Mali GPU its july and there isnt a solution

**Comment by Ji-El974** [comment]
hello, I sometimes manage to pass the cutscenes at the beginning but I never manage to play the game. I have a Redmi note 8 pro.  Thanks

**Comment by deividariel0909** [comment]
Melhoria de compatibilidade com gpu mali caso necessite de log avisa meu celular:a20

**Comment by Ji-El974** [comment]
Hye, with the last version i can play Sonic mania

**Comment by ibmeto** [comment]
On my Samsung note 9 (exynos) sonic mania is working again...

But celeste, super meat boy axiom verge, owlboy are not playable

**Comment by ChrisM20** [comment]
Sonic manía finally fixed and running fine
![Screenshot_20220715_231314_skyline emu](https://user-images.githubusercontent.com/60308449/179338870-2d58b7b7-e512-425e-9f44-8de521beb120.jpg)
![Screenshot_20220715_231355_skyline emu](https://user-images.githubusercontent.com/60308449/179338872-4afc6804-ae3c-4a6f-9158-11f0d42b5ddc.jpg)

**Comment by lynxnb** [comment]
As of cbc896c8f8230a92cffbfdf1c57017b245a0cdb6, all known Mali crashes should be fixed, and all games that work on Adreno GPUs should also work on Mali ones.

**Comment by lynxnb** [comment]
Since this issue is getting fairly large, and being mostly outdated, I'll be closing it. Feel free to open new issues if new crashes appear only on Mali. Please get in touch with us on Discord before doing so, and please do not open issues for graphical issues/glitches for the time being, as they are expected.

**Comment by KYM201** [comment]
Tengo uno con procesador snapdragon 860 creo ques suficiente para poder
emular el Skyline

**Comment by Vijaysolanki679** [comment]
Please solve the problem I have sd 888 bit it still not working solve Mali
GPU in next update please 🥺🥺

**Comment by axeld57** [comment]
Debug
